#!/bin/bash

read y

for args in $(ls ./files/)
do
	ls ./files/
	echo $args
	cp $args buf.txt
	wc -m $args > sizetmp
	x=$(cut -d' ' -f 1 sizetmp)
	if [ echo $args | grep .txt $(ls ./files/) ]
	then
		while  [ $y -gt $x ]
		do
        		cat $args ./files/updater > tmp.txt
        		cp tmp.txt ./files/$args
        		wc -m $args > sizetmp
        		x=$(cut -d' ' -f 1 sizetmp)
		done
	else
		echo "kavo" 
	fi
	cat $args
	echo "---------------------------------------------------------------"
	cp buf.txt $args
	done
done


